version: 2

sources:
   - name: raw
     database: tactile-bindery-475410-f3
     schema: gz_raw_data 
     loader: bigquery
     description: this is the raw data
     freshness:
       warn_after: {count: 12, period: hour}
       error_after: {count: 24, period: hour}
     tables:
       - name: sales
         identifier: raw_gz_sales
         description: this is the raw sales data
         tests:
            - unique:
                column_name: "(orders_id||'-'||pdt_id)"
       - name: product
         identifier: raw_gz_product
         description: this is the raw product data
         columns:
           - name: products_id
             description: ref of the product bought 
             tests:
               - unique
               - not_null
       - name: ship
         identifier: raw_gz_ship
         description: this is the raw shipping data
         columns:
           - name: orders_id
             description: ref of the order
             tests:
               - unique
               - not_null
models:
   - name: int_sales_margin
     description: calculated purchase_cost and margin by joining raw sales and raw product
     columns:
       - name: orders_id
         description: order ref
       - name: products_id
         description: product ref
       - name: date_date
         description: when the order has been placed
       - name: purchase_cost
         description: quantity*purchase_price
       - name: margin
         description: revenue-purchase_cost
             
   - name: int_orders_margin
     description: calculated revenue, quantity, purchase cost, margin group by date and orders
     columns:
       - name: orders_id
         description: orders ref
         tests:
          - unique
          - not_null

   - name: int_orders_operational
     description: calculated operational margin
     columns:
       - name: orders_id
         description: orders ref
         tests:
          - unique
          - not_null








